# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execute',
            old_name='c_ip',
            new_name='computer_ip',
        ),
        migrations.RenameField(
            model_name='execute',
            old_name='s_ip',
            new_name='storage_ip',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='desc',
            new_name='job_desc',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='file',
            new_name='job_file',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='priority',
            new_name='job_priority',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='stat',
            new_name='job_stat',
        ),
    ]
